### ISSUE TITLE
INFO abfrage fehler haft in der fxmanifest

### ISSUE THREAD

**Issue by Sina30** [zRxnx/zrx_personalmenu#1]
Ich Habe die version 1.1.0 runtergeladen und die txadmin Console wird voll gespammt mit den misst das es die version 1.0.0 ist was aber nicht ist also muss man es manuell eingeben 
[script:zrx_personalm] [INFO] zrx_personalmenu is up to date! (1.0.0)

**Comment by Sina30** [comment]
Man bekommt auch Fehler
[    c-scripting-core] InvokeNative: execution failed: std::bad_cast
[script:zrx_personalm] SCRIPT ERROR: Execution of native 000000006b171e87 in script host failed: std::bad_cast
[script:zrx_personalm] > callbackResponse (@ox_lib/callback/server.lua:60)
[script:zrx_personalm] > handler (@ox_lib/callback/server.lua:76)
[script:zrx_personalm] > <unknown> (@oxmysql/dist/build.js:21810)
[script:zrx_personalm] > runMicrotasks (<anonymous>:0)
[script:zrx_personalm] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by zRxnx** [comment]
Wenns nochmal dazu kommt bitte nochmal ein Issue öffnen, hab es eventuell Übersehen? xD
