### ISSUE TITLE
3 Optionen die bei mir nicht gehen wenn ich das Menü öffne.

### ISSUE THREAD

**Issue by GGamer97** [zRxnx/zrx_personalmenu#10]
Die Informations Option und die Bills Option und die Company Option geht nicht bei mir bekomme immer ein Fehler.

[    727453] [b2545_GTAProce]             MainThrd/ error during NUI callback clickContext: citizen:/scripting/lua/scheduler.lua:739: ^1SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: ^1SCRIPT ERROR: @zrx_personalmenu/client/functions.lua:1561: bad argument #1 to 'for iterator' (table expected, got nil)^7
[    727453] [b2545_GTAProce]             MainThrd/ ^3> OpenBillMenu^7 (^5@zrx_personalmenu/client/functions.lua^7:1561)
[    727453] [b2545_GTAProce]             MainThrd/ ^3> ref^7 (^5@zrx_personalmenu/client/functions.lua^7:377)
[    727453] [b2545_GTAProce]             MainThrd/ ^7
[    727468] [b2545_GTAProce]             MainThrd/ 
[    734093] [b2545_GTAProce]             MainThrd/ error during NUI callback clickContext: citizen:/scripting/lua/scheduler.lua:739: ^1SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: ^1SCRIPT ERROR: @zrx_personalmenu/client/functions.lua:1650: attempt to index a nil value (local 'DATA_SOCIETY')^7
[    734093] [b2545_GTAProce]             MainThrd/ ^7
[    734093] [b2545_GTAProce]             MainThrd/

**Comment by GGamer97** [comment]
Das hier hätte ich auch noch was in der Konsole steht
![test](https://github.com/zRxnx/zrx_personalmenu/assets/167695781/e1c7f29e-9cdf-46f6-aa9b-2e398cddff2c)

**Comment by GGamer97** [comment]
![test](https://github.com/zRxnx/zrx_personalmenu/assets/167695781/edbe1db9-d871-4ea8-83f8-66d57d0214f0)

Das hier auch noch

**Comment by zRxnx** [comment]
The framework ox isnt supported by the utility yet

**Comment by GGamer97** [comment]
Ok und was kann ich tun das es geht ?

Sorry i hope you can speak German my English is not the yellow from the egg xD

**Comment by GGamer97** [comment]
Ich habe das Framework esx nämlich deswegen Verstehe ich es nicht ganz wie ich es ändern kann.

**Comment by zRxnx** [comment]
Do you also have ox_core on your server?

**Comment by GGamer97** [comment]
No i use esx

**Comment by zRxnx** [comment]
Well, then the error wouldnt appear.

Bcs it says the error comes from the ox.lua, this lua is only loaded if you have a resource on your server called "ox_core".
Doesnt matter if its stopped or started

**Comment by GGamer97** [comment]
Thank you, now almost everything works except for the boss menu for jobs. 

Is there actually an update soon where accessories like backpacks and so on will be added to the menu?

**Comment by GGamer97** [comment]
![test](https://github.com/zRxnx/zrx_personalmenu/assets/167695781/fb4ab0af-9060-4707-ab71-6744a33544a1)

So I can't really understand why that doesn't work

**Comment by zRxnx** [comment]
try to remove this line

**Comment by GGamer97** [comment]
Nope its not working. 

BRIDGE.getSocietyObject = function(job)
    local self = {}
    self.job = job
    self.money = self.getSocietyMoney()

    self.getSocietyMoney = function()
        local p = promise.new()
        local money = 0

        TriggerEvent('esx_addonaccount:getSharedAccount', 'society_' .. self.job, function(account)
            money = account.money
            p:resolve()
        end)

        Citizen.Await(p)

        return money
    end

    self.addSocietyMoney = function(amount)
        if not amount then
            return 'fail', 'Invalid data passed'
        end

        TriggerEvent('esx_addonaccount:getSharedAccount', 'society_' .. self.job, function(account)
            account.addMoney(amount)
        end)

        return 'success'
    end

    self.setSocietyMoney = function(amount)
        if not amount then
            return 'fail', 'Invalid data passed'
        end

        TriggerEvent('esx_addonaccount:getSharedAccount', 'society_' .. self.job, function(account)
            account.setMoney(amount)
        end)

        return 'success'
    end

    self.removeSocietyMoney = function(amount)
        if not amount then
            return 'fail', 'Invalid data passed'
        end

        TriggerEvent('esx_addonaccount:getSharedAccount', 'society_' .. self.job, function(account)
            account.removeMoney(amount)
        end)

        return 'success'
    end

    return self
end

**Comment by zRxnx** [comment]
you have to remove the line

**Comment by GGamer97** [comment]
I have but its not working

**Comment by Elurym** [comment]
Hello,

Same problem

**Comment by GGamer97** [comment]
> you have to remove the line

You can help us now ?

**Comment by zRxnx** [comment]
Latest Utility and personalmenu version fixes this.
