### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Elurym** [zRxnx/zrx_personalmenu#11]
Hello,

Problem when I click on bills with the last update
![FiveM_b3095_GTAProcess_3CRA2u6AnW](https://github.com/zRxnx/zrx_personalmenu/assets/13484498/b0c46756-483b-4ead-87bc-179a84510b19)
And

Problem when I click on company
![opera_z5qmR96M0i](https://github.com/zRxnx/zrx_personalmenu/assets/13484498/4f1ef027-6f6e-42e4-9499-d26fce923ddd)

**Comment by zRxnx** [comment]
Latest Utility and personalmenu version fixes this.
