### ISSUE TITLE
New Clothing Option ?

### ISSUE THREAD

**Issue by GGamer97** [zRxnx/zrx_personalmenu#12]
Hello.

Can you add a Clothing Option for the trousers and for the Backpack ?

**Comment by zRxnx** [comment]
Is alrdy in there

**Comment by GGamer97** [comment]
> Is alrdy in there

Oh i can not find it in there

**Comment by zRxnx** [comment]
Pants and bag

**Comment by GGamer97** [comment]
Yes. But i only have.

hat

Mask

ears

glasses

shirt 

torso

**Comment by zRxnx** [comment]
I cant fix things that are not broken

**Comment by GGamer97** [comment]
I can even send you a proof that it does not work although I have reinstalled it even

**Comment by zRxnx** [comment]
Well, just look into the showcase video, everything works. Its also in the code, just look
