### ISSUE TITLE
Add Rockstar Editor for this

### ISSUE THREAD

**Issue by jcrey16-git** [zRxnx/zrx_personalmenu#5]
Hi there!! I know its not a issue itself but... i love your script dude. It's the most simple and yet best script free of personal menu out there and i'm here to suggest if you can add the Rockstar Editor for clips and things like that. ¡It would be a good addition! I'm not a LUA Developer but my server need it for the purpose of just doing clips. ¡Thx for all hard work!

**Comment by zRxnx** [comment]
Hmm dont know much abt the editor but will look

**Comment by zRxnx** [comment]
Added
