### ISSUE TITLE
Cant hire players

### ISSUE THREAD

**Issue by Tilltheprogamer** [zRxnx/zrx_personalmenu#8]
I cant hire nearby players via the firm menu.

**Comment by Tilltheprogamer** [comment]
and if i open the menu before i select anything the menu cursor is stuck

**Comment by Tilltheprogamer** [comment]
I made a pull request where the problems was fixed

**Comment by Tilltheprogamer** [comment]
But theres a new problem 

[script:zrx_personalm] SCRIPT ERROR: @zrx_personalmenu/server/functions.lua:44: attempt to call a nil value (field 'getName')

**Comment by zRxnx** [comment]
Is it still with the latest one?

**Comment by Tilltheprogamer** [comment]
What do you mean ?

**Comment by Tilltheprogamer** [comment]
The version yes its 2.5.1

**Comment by zRxnx** [comment]
latest is 2.6.0

**Comment by Tilltheprogamer** [comment]
I just saw that

**Comment by Tilltheprogamer** [comment]
I keep ya posted if the bugs still apply

**Comment by Tilltheprogamer** [comment]
nope still errors and the menu selection isnt moveing when you open the menu 
![image](https://github.com/zRxnx/zrx_personalmenu/assets/118006357/48d268be-c58b-4cb6-b169-70e9eb3d8401)

**Comment by zRxnx** [comment]
you use the latest utlity right?

**Comment by Tilltheprogamer** [comment]
with your 2.0.0 util its not even opening anymore 
![image](https://github.com/zRxnx/zrx_personalmenu/assets/118006357/7a618edf-da8d-4527-bbcb-84cfad769a97)

**Comment by GGamer97** [comment]
> with your 2.0.0 util its not even opening anymore ![image](https://private-user-images.githubusercontent.com/118006357/324251149-7a618edf-da8d-4527-bbcb-84cfad769a97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTEwMDksIm5iZiI6MTcxMzcxMDcwOSwicGF0aCI6Ii8xMTgwMDYzNTcvMzI0MjUxMTQ5LTdhNjE4ZWRmLWRhOGQtNDUyNy1iYmNiLTg0Y2ZhZDc2OWE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxNDQ1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzI3ZmI3MDMyMWU1MmY0ZGFmNGRmNjA3NzZiYWViMTllMjMzZTliZDNkZjlmZmE3ZjVkNzE3NGIxNmJmY2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DMZ7bMC_8_ogwUlKG9kyo7C7x3YtzIipSHGGLrdnslY)

I have the same Problem i can not open it and i have all up to date. Pls help

**Comment by zRxnx** [comment]
will look

**Comment by zRxnx** [comment]
latest version of utility should do it

**Comment by GGamer97** [comment]
> latest version of utility should do it

I have download it and is not working for me
![test](https://github.com/zRxnx/zrx_personalmenu/assets/167695781/af5679eb-fe7a-4b34-bfa0-c5be6e41691a)

**Comment by zRxnx** [comment]
then try now 2.6.1 of perso xD

**Comment by GGamer97** [comment]
Thanks is now working :D

I still have 3 problems can I write them here?

**Comment by zRxnx** [comment]
> I still have 3 problems can I write them here?

Better create a new thread/issue
